version: '3'
services:
  reach-app:
    image: reachsh/examples-multisig:v0.1.1
    build: .
    depends_on:
      - devnet
    environment:
      - ETH_NODE_URI=http://devnet:8545
  devnet:
    image: reachsh/ethereum-devnet:v0.1.1
    
