version: '3.4'
x-app-base: &app-base
  image: reachsh/reach-app-duoswap:latest
services:
  devnet-cfx:
    image: reachsh/devnet-cfx:0.1
  devnet-eth:
    image: reachsh/devnet-eth:0.1
  devnet-algo:
    image: reachsh/devnet-algo:0.1
    depends_on:
      - devnet-algo-pg
    environment:
      - REACH_ALGO_DEBUG
      - POSTGRES_HOST=devnet-algo-pg
      - POSTGRES_USER=algogrand
      - POSTGRES_PASSWORD=indexer
      - POSTGRES_DB=pgdb
    ports:
      - 9392
  devnet-algo-pg:
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=algogrand
      - POSTGRES_PASSWORD=indexer
      - POSTGRES_DB=pgdb
  reach-app-duoswap-ETH-live:
    <<: *app-base
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ETH-live
      - REACH_ISOLATED_NETWORK
      - ETH_NODE_URI
      - ETH_NODE_NETWORK
  reach-app-duoswap-ETH-devnet: &default-app
    <<: *app-base
    depends_on:
      - devnet-eth
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ETH-devnet
      - ETH_NODE_URI=http://devnet-eth:8545
  reach-app-duoswap-ALGO-live:
    <<: *app-base
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ALGO-live
      - REACH_ISOLATED_NETWORK
      - ALGO_TOKEN
      - ALGO_SERVER
      - ALGO_PORT
      - ALGO_INDEXER_TOKEN
      - ALGO_INDEXER_SERVER
      - ALGO_INDEXER_PORT
      - ALGO_FAUCET_PASSPHRASE
  reach-app-duoswap-ALGO-devnet:
    <<: *app-base
    depends_on:
      - devnet-algo
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=ALGO-devnet
      - ALGO_SERVER=http://devnet-algo
      - ALGO_PORT=4180
      - ALGO_INDEXER_SERVER=http://devnet-algo
      - ALGO_INDEXER_PORT=8980
  reach-app-duoswap-CFX-devnet:
    <<: *app-base
    depends_on:
      - devnet-cfx
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=CFX-devnet
      - CFX_DEBUG
      - CFX_NODE_URI=http://devnet-cfx:12537
      - CFX_NETWORK_ID=999
  reach-app-duoswap-CFX-live:
    <<: *app-base
    environment:
      - REACH_DEBUG
      - REACH_CONNECTOR_MODE=CFX-live
      - CFX_DEBUG
      - CFX_NODE_URI
      - CFX_NETWORK_ID
  reach-app-duoswap-: *default-app
  reach-app-duoswap: *default-app
